################################################################################
##
## Core Matter makefile
##
## This file was automatically generated and should not be modified.
##
################################################################################

################################################################################
# INCLUDES
################################################################################

INCLUDES += $(SEARCH_matter)/src                                                          \
            $(SEARCH_matter)/src/access                                                   \
            $(SEARCH_matter)/src/access/examples                                          \
            $(SEARCH_matter)/src/app/MessageDef                                           \
            $(SEARCH_matter)/src/app/data-model                                           \
            $(SEARCH_matter)/src/app/data-model-provider                                  \
            $(SEARCH_matter)/src/app/icd/server                                           \
            $(SEARCH_matter)/src/app/reporting                                            \
            $(SEARCH_matter)/src/app/server                                               \
            $(SEARCH_matter)/src/app/server-cluster                                       \
            $(SEARCH_matter)/src/app/util                                                 \
            $(SEARCH_matter)/src/app/util/persistence                                     \
            $(SEARCH_matter)/src/ble                                                      \
            $(SEARCH_matter)/src/controller                                               \
            $(SEARCH_matter)/src/credentials                                              \
            $(SEARCH_matter)/src/credentials/attestation_verifier                         \
            $(SEARCH_matter)/src/credentials/examples                                     \
            $(SEARCH_matter)/src/crypto                                                   \
            $(SEARCH_matter)/src/data-model-providers/codegen                             \
            $(SEARCH_matter)/src/include                                                  \
            $(SEARCH_matter)/src/inet                                                     \
            $(SEARCH_matter)/src/lib                                                      \
            $(SEARCH_matter)/src/lib/address_resolve                                      \
            $(SEARCH_matter)/src/lib/asn1                                                 \
            $(SEARCH_matter)/src/lib/core                                                 \
            $(SEARCH_matter)/src/lib/dnssd                                                \
            $(SEARCH_matter)/src/lib/dnssd/minimal_mdns                                   \
            $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/core                              \
            $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/records                           \
            $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/responders                        \
            $(SEARCH_matter)/src/lib/support                                              \
            $(SEARCH_matter)/src/lib/support/logging                                      \
            $(SEARCH_matter)/src/lib/support/verhoeff                                     \
            $(SEARCH_matter)/src/messaging                                                \
            $(SEARCH_matter)/src/platform                                                 \
            $(SEARCH_matter)/src/platform/logging/impl                                    \
            $(SEARCH_matter)/src/protocols                                                \
            $(SEARCH_matter)/src/protocols/bdx                                            \
            $(SEARCH_matter)/src/protocols/echo                                           \
            $(SEARCH_matter)/src/protocols/interaction_model                              \
            $(SEARCH_matter)/src/protocols/secure_channel                                 \
            $(SEARCH_matter)/src/protocols/user_directed_commissioning                    \
            $(SEARCH_matter)/src/setup_payload                                            \
            $(SEARCH_matter)/src/system                                                   \
            $(SEARCH_matter)/src/tracing                                                  \
            $(SEARCH_matter)/src/tracing/json                                             \
            $(SEARCH_matter)/src/transport                                                \
            $(SEARCH_matter)/src/transport/raw                                            \
            $(SEARCH_matter)/third_party/infineon/psoc6                                   \
            $(SEARCH_matter)/third_party/nlassert/repo/include                            \
            $(SEARCH_matter)/third_party/nlio/repo/include                                \
            $(SEARCH_matter)/zzz_generated/app-common                                     \
            $(SEARCH_matter)/zzz_generated/app-common/app-common/zap-generated            \
            $(SEARCH_matter)/zzz_generated/app-common/app-common/zap-generated/attributes


################################################################################
# SOURCES
################################################################################

SOURCES += $(SEARCH_matter)/src/access/AccessControl.cpp                                                  \
           $(SEARCH_matter)/src/access/examples/ExampleAccessControlDelegate.cpp                          \
           $(SEARCH_matter)/src/access/examples/PermissiveAccessControlDelegate.cpp                       \
           $(SEARCH_matter)/src/app/AttributeAccessInterfaceRegistry.cpp                                  \
           $(SEARCH_matter)/src/app/AttributePathExpandIterator.cpp                                       \
           $(SEARCH_matter)/src/app/AttributeReportBuilder.cpp                                            \
           $(SEARCH_matter)/src/app/AttributeValueEncoder.cpp                                             \
           $(SEARCH_matter)/src/app/BufferedReadCallback.cpp                                              \
           $(SEARCH_matter)/src/app/CASEClient.cpp                                                        \
           $(SEARCH_matter)/src/app/CASESessionManager.cpp                                                \
           $(SEARCH_matter)/src/app/ChunkedWriteCallback.cpp                                              \
           $(SEARCH_matter)/src/app/ClusterStateCache.cpp                                                 \
           $(SEARCH_matter)/src/app/CommandHandler.cpp                                                    \
           $(SEARCH_matter)/src/app/CommandHandlerImpl.cpp                                                \
           $(SEARCH_matter)/src/app/CommandHandlerInterfaceRegistry.cpp                                   \
           $(SEARCH_matter)/src/app/CommandResponseSender.cpp                                             \
           $(SEARCH_matter)/src/app/CommandSender.cpp                                                     \
           $(SEARCH_matter)/src/app/DeviceProxy.cpp                                                       \
           $(SEARCH_matter)/src/app/EventManagement.cpp                                                   \
           $(SEARCH_matter)/src/app/FailSafeContext.cpp                                                   \
           $(SEARCH_matter)/src/app/GenericEventManagementTestEventTriggerHandler.cpp                     \
           $(SEARCH_matter)/src/app/GlobalAttributes.cpp                                                  \
           $(SEARCH_matter)/src/app/InteractionModelDelegatePointers.cpp                                  \
           $(SEARCH_matter)/src/app/InteractionModelEngine.cpp                                            \
           $(SEARCH_matter)/src/app/MessageDef/ArrayBuilder.cpp                                           \
           $(SEARCH_matter)/src/app/MessageDef/ArrayParser.cpp                                            \
           $(SEARCH_matter)/src/app/MessageDef/AttributeDataIB.cpp                                        \
           $(SEARCH_matter)/src/app/MessageDef/AttributeDataIBs.cpp                                       \
           $(SEARCH_matter)/src/app/MessageDef/AttributePathIB.cpp                                        \
           $(SEARCH_matter)/src/app/MessageDef/AttributePathIBs.cpp                                       \
           $(SEARCH_matter)/src/app/MessageDef/AttributeReportIB.cpp                                      \
           $(SEARCH_matter)/src/app/MessageDef/AttributeReportIBs.cpp                                     \
           $(SEARCH_matter)/src/app/MessageDef/AttributeStatusIB.cpp                                      \
           $(SEARCH_matter)/src/app/MessageDef/AttributeStatusIBs.cpp                                     \
           $(SEARCH_matter)/src/app/MessageDef/Builder.cpp                                                \
           $(SEARCH_matter)/src/app/MessageDef/ClusterPathIB.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/CommandDataIB.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/CommandPathIB.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/CommandStatusIB.cpp                                        \
           $(SEARCH_matter)/src/app/MessageDef/DataVersionFilterIB.cpp                                    \
           $(SEARCH_matter)/src/app/MessageDef/DataVersionFilterIBs.cpp                                   \
           $(SEARCH_matter)/src/app/MessageDef/EventDataIB.cpp                                            \
           $(SEARCH_matter)/src/app/MessageDef/EventFilterIB.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/EventFilterIBs.cpp                                         \
           $(SEARCH_matter)/src/app/MessageDef/EventPathIB.cpp                                            \
           $(SEARCH_matter)/src/app/MessageDef/EventPathIBs.cpp                                           \
           $(SEARCH_matter)/src/app/MessageDef/EventReportIB.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/EventReportIBs.cpp                                         \
           $(SEARCH_matter)/src/app/MessageDef/EventStatusIB.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/InvokeRequestMessage.cpp                                   \
           $(SEARCH_matter)/src/app/MessageDef/InvokeRequests.cpp                                         \
           $(SEARCH_matter)/src/app/MessageDef/InvokeResponseIB.cpp                                       \
           $(SEARCH_matter)/src/app/MessageDef/InvokeResponseIBs.cpp                                      \
           $(SEARCH_matter)/src/app/MessageDef/InvokeResponseMessage.cpp                                  \
           $(SEARCH_matter)/src/app/MessageDef/ListBuilder.cpp                                            \
           $(SEARCH_matter)/src/app/MessageDef/ListParser.cpp                                             \
           $(SEARCH_matter)/src/app/MessageDef/MessageBuilder.cpp                                         \
           $(SEARCH_matter)/src/app/MessageDef/MessageDefHelper.cpp                                       \
           $(SEARCH_matter)/src/app/MessageDef/MessageParser.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/Parser.cpp                                                 \
           $(SEARCH_matter)/src/app/MessageDef/ReadRequestMessage.cpp                                     \
           $(SEARCH_matter)/src/app/MessageDef/ReportDataMessage.cpp                                      \
           $(SEARCH_matter)/src/app/MessageDef/StatusIB.cpp                                               \
           $(SEARCH_matter)/src/app/MessageDef/StatusResponseMessage.cpp                                  \
           $(SEARCH_matter)/src/app/MessageDef/StructBuilder.cpp                                          \
           $(SEARCH_matter)/src/app/MessageDef/StructParser.cpp                                           \
           $(SEARCH_matter)/src/app/MessageDef/SubscribeRequestMessage.cpp                                \
           $(SEARCH_matter)/src/app/MessageDef/SubscribeResponseMessage.cpp                               \
           $(SEARCH_matter)/src/app/MessageDef/TimedRequestMessage.cpp                                    \
           $(SEARCH_matter)/src/app/MessageDef/WriteRequestMessage.cpp                                    \
           $(SEARCH_matter)/src/app/MessageDef/WriteResponseMessage.cpp                                   \
           $(SEARCH_matter)/src/app/OperationalSessionSetup.cpp                                           \
           $(SEARCH_matter)/src/app/PendingResponseTrackerImpl.cpp                                        \
           $(SEARCH_matter)/src/app/ReadClient.cpp                                                        \
           $(SEARCH_matter)/src/app/ReadHandler.cpp                                                       \
           $(SEARCH_matter)/src/app/SafeAttributePersistenceProvider.cpp                                  \
           $(SEARCH_matter)/src/app/StatusResponse.cpp                                                    \
           $(SEARCH_matter)/src/app/StorageDelegateWrapper.cpp                                            \
           $(SEARCH_matter)/src/app/TimedHandler.cpp                                                      \
           $(SEARCH_matter)/src/app/TimedRequest.cpp                                                      \
           $(SEARCH_matter)/src/app/TimerDelegates.cpp                                                    \
           $(SEARCH_matter)/src/app/WriteClient.cpp                                                       \
           $(SEARCH_matter)/src/app/WriteHandler.cpp                                                      \
           $(SEARCH_matter)/src/app/data-model-provider/ActionReturnStatus.cpp                            \
           $(SEARCH_matter)/src/app/data-model-provider/MetadataLookup.cpp                                \
           $(SEARCH_matter)/src/app/data-model-provider/ProviderMetadataTree.cpp                          \
           $(SEARCH_matter)/src/app/data-model/FabricScopedPreEncodedValue.cpp                            \
           $(SEARCH_matter)/src/app/data-model/PreEncodedValue.cpp                                        \
           $(SEARCH_matter)/src/app/data-model/StructDecodeIterator.cpp                                   \
           $(SEARCH_matter)/src/app/data-model/WrappedStructEncoder.cpp                                   \
           $(SEARCH_matter)/src/app/icd/server/ICDConfigurationData.cpp                                   \
           $(SEARCH_matter)/src/app/icd/server/ICDManager.cpp                                             \
           $(SEARCH_matter)/src/app/icd/server/ICDMonitoringTable.cpp                                     \
           $(SEARCH_matter)/src/app/icd/server/ICDNotifier.cpp                                            \
           $(SEARCH_matter)/src/app/reporting/Engine.cpp                                                  \
           $(SEARCH_matter)/src/app/reporting/ReportSchedulerImpl.cpp                                     \
           $(SEARCH_matter)/src/app/reporting/SynchronizedReportSchedulerImpl.cpp                         \
           $(SEARCH_matter)/src/app/reporting/reporting.cpp                                               \
           $(SEARCH_matter)/src/app/server-cluster/DefaultServerCluster.cpp                               \
           $(SEARCH_matter)/src/app/server-cluster/ServerClusterInterface.cpp                             \
           $(SEARCH_matter)/src/app/server/AclStorage.cpp                                                 \
           $(SEARCH_matter)/src/app/server/CommissioningWindowManager.cpp                                 \
           $(SEARCH_matter)/src/app/server/DefaultAclStorage.cpp                                          \
           $(SEARCH_matter)/src/app/server/DefaultTermsAndConditionsProvider.cpp                          \
           $(SEARCH_matter)/src/app/server/Dnssd.cpp                                                      \
           $(SEARCH_matter)/src/app/server/EchoHandler.cpp                                                \
           $(SEARCH_matter)/src/app/server/JointFabricDatastore.cpp                                       \
           $(SEARCH_matter)/src/app/server/Server.cpp                                                     \
           $(SEARCH_matter)/src/app/server/TermsAndConditionsManager.cpp                                  \
           $(SEARCH_matter)/src/app/util/DataModelHandler.cpp                                             \
           $(SEARCH_matter)/src/app/util/MatterCallbacks.cpp                                              \
           $(SEARCH_matter)/src/app/util/attribute-metadata.cpp                                           \
           $(SEARCH_matter)/src/app/util/attribute-storage.cpp                                            \
           $(SEARCH_matter)/src/app/util/attribute-table.cpp                                              \
           $(SEARCH_matter)/src/app/util/binding-table.cpp                                                \
           $(SEARCH_matter)/src/app/util/ember-io-storage.cpp                                             \
           $(SEARCH_matter)/src/app/util/ember-strings.cpp                                                \
           $(SEARCH_matter)/src/app/util/generic-callback-stubs.cpp                                       \
           $(SEARCH_matter)/src/app/util/persistence/AttributePersistenceProvider.cpp                     \
           $(SEARCH_matter)/src/app/util/persistence/DefaultAttributePersistenceProvider.cpp              \
           $(SEARCH_matter)/src/app/util/persistence/DeferredAttributePersistenceProvider.cpp             \
           $(SEARCH_matter)/src/app/util/privilege-storage.cpp                                            \
           $(SEARCH_matter)/src/app/util/util.cpp                                                         \
           $(SEARCH_matter)/src/ble/BLEEndPoint.cpp                                                       \
           $(SEARCH_matter)/src/ble/BleError.cpp                                                          \
           $(SEARCH_matter)/src/ble/BleLayer.cpp                                                          \
           $(SEARCH_matter)/src/ble/BleUUID.cpp                                                           \
           $(SEARCH_matter)/src/ble/BtpEngine.cpp                                                         \
           $(SEARCH_matter)/src/credentials/CHIPCert.cpp                                                  \
           $(SEARCH_matter)/src/credentials/CHIPCertFromX509.cpp                                          \
           $(SEARCH_matter)/src/credentials/CHIPCertToX509.cpp                                            \
           $(SEARCH_matter)/src/credentials/CertificationDeclaration.cpp                                  \
           $(SEARCH_matter)/src/credentials/DeviceAttestationConstructor.cpp                              \
           $(SEARCH_matter)/src/credentials/DeviceAttestationCredsProvider.cpp                            \
           $(SEARCH_matter)/src/credentials/FabricTable.cpp                                               \
           $(SEARCH_matter)/src/credentials/GenerateChipX509Cert.cpp                                      \
           $(SEARCH_matter)/src/credentials/GroupDataProviderImpl.cpp                                     \
           $(SEARCH_matter)/src/credentials/LastKnownGoodTime.cpp                                         \
           $(SEARCH_matter)/src/credentials/PersistentStorageOpCertStore.cpp                              \
           $(SEARCH_matter)/src/credentials/attestation_verifier/DacOnlyPartialAttestationVerifier.cpp    \
           $(SEARCH_matter)/src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp     \
           $(SEARCH_matter)/src/credentials/attestation_verifier/DeviceAttestationVerifier.cpp            \
           $(SEARCH_matter)/src/credentials/attestation_verifier/TestPAAStore.cpp                         \
           $(SEARCH_matter)/src/credentials/examples/DeviceAttestationCredsExample.cpp                    \
           $(SEARCH_matter)/src/credentials/examples/ExampleDACs.cpp                                      \
           $(SEARCH_matter)/src/credentials/examples/ExamplePAI.cpp                                       \
           $(SEARCH_matter)/src/crypto/CHIPCryptoPAL.cpp                                                  \
           $(SEARCH_matter)/src/crypto/CHIPCryptoPALmbedTLS.cpp                                           \
           $(SEARCH_matter)/src/crypto/CHIPCryptoPALmbedTLSCert.cpp                                       \
           $(SEARCH_matter)/src/crypto/PersistentStorageOperationalKeystore.cpp                           \
           $(SEARCH_matter)/src/crypto/RandUtils.cpp                                                      \
           $(SEARCH_matter)/src/crypto/RawKeySessionKeystore.cpp                                          \
           $(SEARCH_matter)/src/data-model-providers/codegen/CodegenDataModelProvider.cpp                 \
           $(SEARCH_matter)/src/data-model-providers/codegen/CodegenDataModelProvider_Read.cpp            \
           $(SEARCH_matter)/src/data-model-providers/codegen/CodegenDataModelProvider_Write.cpp           \
           $(SEARCH_matter)/src/data-model-providers/codegen/EmberAttributeDataBuffer.cpp                 \
           $(SEARCH_matter)/src/data-model-providers/codegen/EmberMetadata.cpp                            \
           $(SEARCH_matter)/src/data-model-providers/codegen/Instance.cpp                                 \
           $(SEARCH_matter)/src/data-model-providers/codegen/ServerClusterInterfaceRegistry.cpp           \
           $(SEARCH_matter)/src/inet/EndPointStateLwIP.cpp                                                \
           $(SEARCH_matter)/src/inet/IPAddress-StringFuncts.cpp                                           \
           $(SEARCH_matter)/src/inet/IPAddress.cpp                                                        \
           $(SEARCH_matter)/src/inet/IPPacketInfo.cpp                                                     \
           $(SEARCH_matter)/src/inet/IPPrefix.cpp                                                         \
           $(SEARCH_matter)/src/inet/InetArgParser.cpp                                                    \
           $(SEARCH_matter)/src/inet/InetError.cpp                                                        \
           $(SEARCH_matter)/src/inet/InetInterface.cpp                                                    \
           $(SEARCH_matter)/src/inet/InetInterfaceImplDefault.cpp                                         \
           $(SEARCH_matter)/src/inet/TCPEndPoint.cpp                                                      \
           $(SEARCH_matter)/src/inet/TCPEndPointImplLwIP.cpp                                              \
           $(SEARCH_matter)/src/inet/UDPEndPoint.cpp                                                      \
           $(SEARCH_matter)/src/inet/UDPEndPointImplLwIP.cpp                                              \
           $(SEARCH_matter)/src/lib/address_resolve/AddressResolve.cpp                                    \
           $(SEARCH_matter)/src/lib/address_resolve/AddressResolve_DefaultImpl.cpp                        \
           $(SEARCH_matter)/src/lib/asn1/ASN1Error.cpp                                                    \
           $(SEARCH_matter)/src/lib/asn1/ASN1OID.cpp                                                      \
           $(SEARCH_matter)/src/lib/asn1/ASN1Reader.cpp                                                   \
           $(SEARCH_matter)/src/lib/asn1/ASN1Time.cpp                                                     \
           $(SEARCH_matter)/src/lib/asn1/ASN1Writer.cpp                                                   \
           $(SEARCH_matter)/src/lib/core/CHIPError.cpp                                                    \
           $(SEARCH_matter)/src/lib/core/CHIPKeyIds.cpp                                                   \
           $(SEARCH_matter)/src/lib/core/ErrorStr.cpp                                                     \
           $(SEARCH_matter)/src/lib/core/OTAImageHeader.cpp                                               \
           $(SEARCH_matter)/src/lib/core/TLVCircularBuffer.cpp                                            \
           $(SEARCH_matter)/src/lib/core/TLVDebug.cpp                                                     \
           $(SEARCH_matter)/src/lib/core/TLVReader.cpp                                                    \
           $(SEARCH_matter)/src/lib/core/TLVTags.cpp                                                      \
           $(SEARCH_matter)/src/lib/core/TLVUpdater.cpp                                                   \
           $(SEARCH_matter)/src/lib/core/TLVUtilities.cpp                                                 \
           $(SEARCH_matter)/src/lib/core/TLVWriter.cpp                                                    \
           $(SEARCH_matter)/src/lib/dnssd/ActiveResolveAttempts.cpp                                       \
           $(SEARCH_matter)/src/lib/dnssd/Advertiser.cpp                                                  \
           $(SEARCH_matter)/src/lib/dnssd/Advertiser_ImplMinimalMdns.cpp                                  \
           $(SEARCH_matter)/src/lib/dnssd/IPAddressSorter.cpp                                             \
           $(SEARCH_matter)/src/lib/dnssd/IncrementalResolve.cpp                                          \
           $(SEARCH_matter)/src/lib/dnssd/MinimalMdnsServer.cpp                                           \
           $(SEARCH_matter)/src/lib/dnssd/Resolver.cpp                                                    \
           $(SEARCH_matter)/src/lib/dnssd/ResolverProxy.cpp                                               \
           $(SEARCH_matter)/src/lib/dnssd/Resolver_ImplMinimalMdns.cpp                                    \
           $(SEARCH_matter)/src/lib/dnssd/ServiceNaming.cpp                                               \
           $(SEARCH_matter)/src/lib/dnssd/TxtFields.cpp                                                   \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/AddressPolicy.cpp                                  \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/AddressPolicy_DefaultImpl.cpp                      \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/Parser.cpp                                         \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/RecordData.cpp                                     \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/ResponseSender.cpp                                 \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/Server.cpp                                         \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/core/QName.cpp                                     \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/core/QNameString.cpp                               \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/core/RecordWriter.cpp                              \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/records/IP.cpp                                     \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/records/ResourceRecord.cpp                         \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/responders/IP.cpp                                  \
           $(SEARCH_matter)/src/lib/dnssd/minimal_mdns/responders/QueryResponder.cpp                      \
           $(SEARCH_matter)/src/lib/support/Base64.cpp                                                    \
           $(SEARCH_matter)/src/lib/support/BufferReader.cpp                                              \
           $(SEARCH_matter)/src/lib/support/BufferWriter.cpp                                              \
           $(SEARCH_matter)/src/lib/support/BytesCircularBuffer.cpp                                       \
           $(SEARCH_matter)/src/lib/support/BytesToHex.cpp                                                \
           $(SEARCH_matter)/src/lib/support/CHIPArgParser.cpp                                             \
           $(SEARCH_matter)/src/lib/support/CHIPMem-Malloc.cpp                                            \
           $(SEARCH_matter)/src/lib/support/CHIPMem.cpp                                                   \
           $(SEARCH_matter)/src/lib/support/CHIPPlatformMemory.cpp                                        \
           $(SEARCH_matter)/src/lib/support/FibonacciUtils.cpp                                            \
           $(SEARCH_matter)/src/lib/support/FixedBufferAllocator.cpp                                      \
           $(SEARCH_matter)/src/lib/support/IniEscaping.cpp                                               \
           $(SEARCH_matter)/src/lib/support/PersistentStorageAudit.cpp                                    \
           $(SEARCH_matter)/src/lib/support/Pool.cpp                                                      \
           $(SEARCH_matter)/src/lib/support/PrivateHeap.cpp                                               \
           $(SEARCH_matter)/src/lib/support/ReadOnlyBuffer.cpp                                            \
           $(SEARCH_matter)/src/lib/support/StringBuilder.cpp                                             \
           $(SEARCH_matter)/src/lib/support/ThreadOperationalDataset.cpp                                  \
           $(SEARCH_matter)/src/lib/support/TimeUtils.cpp                                                 \
           $(SEARCH_matter)/src/lib/support/ZclString.cpp                                                 \
           $(SEARCH_matter)/src/lib/support/logging/BinaryLogging.cpp                                     \
           $(SEARCH_matter)/src/lib/support/logging/TextOnlyLogging.cpp                                   \
           $(SEARCH_matter)/src/lib/support/utf8.cpp                                                      \
           $(SEARCH_matter)/src/lib/support/verhoeff/Verhoeff.cpp                                         \
           $(SEARCH_matter)/src/lib/support/verhoeff/Verhoeff10.cpp                                       \
           $(SEARCH_matter)/src/messaging/ApplicationExchangeDispatch.cpp                                 \
           $(SEARCH_matter)/src/messaging/ErrorCategory.cpp                                               \
           $(SEARCH_matter)/src/messaging/ExchangeContext.cpp                                             \
           $(SEARCH_matter)/src/messaging/ExchangeMessageDispatch.cpp                                     \
           $(SEARCH_matter)/src/messaging/ExchangeMgr.cpp                                                 \
           $(SEARCH_matter)/src/messaging/ReliableMessageContext.cpp                                      \
           $(SEARCH_matter)/src/messaging/ReliableMessageMgr.cpp                                          \
           $(SEARCH_matter)/src/messaging/ReliableMessageProtocolConfig.cpp                               \
           $(SEARCH_matter)/src/platform/CommissionableDataProvider.cpp                                   \
           $(SEARCH_matter)/src/platform/DeviceControlServer.cpp                                          \
           $(SEARCH_matter)/src/platform/DeviceInfoProvider.cpp                                           \
           $(SEARCH_matter)/src/platform/DeviceInstanceInfoProvider.cpp                                   \
           $(SEARCH_matter)/src/platform/DiagnosticDataProvider.cpp                                       \
           $(SEARCH_matter)/src/platform/Entropy.cpp                                                      \
           $(SEARCH_matter)/src/platform/GeneralUtils.cpp                                                 \
           $(SEARCH_matter)/src/platform/Globals.cpp                                                      \
           $(SEARCH_matter)/src/platform/LockTracker.cpp                                                  \
           $(SEARCH_matter)/src/platform/PersistedStorage.cpp                                             \
           $(SEARCH_matter)/src/platform/PlatformEventSupport.cpp                                         \
           $(SEARCH_matter)/src/platform/RuntimeOptionsProvider.cpp                                       \
           $(SEARCH_matter)/src/platform/SingletonConfigurationManager.cpp                                \
           $(SEARCH_matter)/src/protocols/Protocols.cpp                                                   \
           $(SEARCH_matter)/src/protocols/bdx/AsyncTransferFacilitator.cpp                                \
           $(SEARCH_matter)/src/protocols/bdx/BdxMessages.cpp                                             \
           $(SEARCH_matter)/src/protocols/bdx/BdxTransferDiagnosticLog.cpp                                \
           $(SEARCH_matter)/src/protocols/bdx/BdxTransferProxyDiagnosticLog.cpp                           \
           $(SEARCH_matter)/src/protocols/bdx/BdxTransferServer.cpp                                       \
           $(SEARCH_matter)/src/protocols/bdx/BdxTransferSession.cpp                                      \
           $(SEARCH_matter)/src/protocols/bdx/BdxUri.cpp                                                  \
           $(SEARCH_matter)/src/protocols/bdx/StatusCode.cpp                                              \
           $(SEARCH_matter)/src/protocols/bdx/TransferFacilitator.cpp                                     \
           $(SEARCH_matter)/src/protocols/echo/EchoClient.cpp                                             \
           $(SEARCH_matter)/src/protocols/echo/EchoServer.cpp                                             \
           $(SEARCH_matter)/src/protocols/interaction_model/StatusCode.cpp                                \
           $(SEARCH_matter)/src/protocols/secure_channel/CASEDestinationId.cpp                            \
           $(SEARCH_matter)/src/protocols/secure_channel/CASEServer.cpp                                   \
           $(SEARCH_matter)/src/protocols/secure_channel/CASESession.cpp                                  \
           $(SEARCH_matter)/src/protocols/secure_channel/CheckInCounter.cpp                               \
           $(SEARCH_matter)/src/protocols/secure_channel/CheckinMessage.cpp                               \
           $(SEARCH_matter)/src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp              \
           $(SEARCH_matter)/src/protocols/secure_channel/MessageCounterManager.cpp                        \
           $(SEARCH_matter)/src/protocols/secure_channel/PASESession.cpp                                  \
           $(SEARCH_matter)/src/protocols/secure_channel/PairingSession.cpp                               \
           $(SEARCH_matter)/src/protocols/secure_channel/SessionEstablishmentExchangeDispatch.cpp         \
           $(SEARCH_matter)/src/protocols/secure_channel/SimpleSessionResumptionStorage.cpp               \
           $(SEARCH_matter)/src/protocols/secure_channel/StatusReport.cpp                                 \
           $(SEARCH_matter)/src/protocols/secure_channel/UnsolicitedStatusHandler.cpp                     \
           $(SEARCH_matter)/src/protocols/user_directed_commissioning/UserDirectedCommissioningClient.cpp \
           $(SEARCH_matter)/src/protocols/user_directed_commissioning/UserDirectedCommissioningServer.cpp \
           $(SEARCH_matter)/src/setup_payload/AdditionalDataPayloadGenerator.cpp                          \
           $(SEARCH_matter)/src/setup_payload/AdditionalDataPayloadParser.cpp                             \
           $(SEARCH_matter)/src/setup_payload/Base38Decode.cpp                                            \
           $(SEARCH_matter)/src/setup_payload/Base38Encode.cpp                                            \
           $(SEARCH_matter)/src/setup_payload/ManualSetupPayloadGenerator.cpp                             \
           $(SEARCH_matter)/src/setup_payload/ManualSetupPayloadParser.cpp                                \
           $(SEARCH_matter)/src/setup_payload/OnboardingCodesUtil.cpp                                     \
           $(SEARCH_matter)/src/setup_payload/QRCodeSetupPayloadGenerator.cpp                             \
           $(SEARCH_matter)/src/setup_payload/QRCodeSetupPayloadParser.cpp                                \
           $(SEARCH_matter)/src/setup_payload/SetupPayload.cpp                                            \
           $(SEARCH_matter)/src/setup_payload/SetupPayloadHelper.cpp                                      \
           $(SEARCH_matter)/src/system/SystemClock.cpp                                                    \
           $(SEARCH_matter)/src/system/SystemError.cpp                                                    \
           $(SEARCH_matter)/src/system/SystemLayer.cpp                                                    \
           $(SEARCH_matter)/src/system/SystemLayerImplFreeRTOS.cpp                                        \
           $(SEARCH_matter)/src/system/SystemMutex.cpp                                                    \
           $(SEARCH_matter)/src/system/SystemPacketBuffer.cpp                                             \
           $(SEARCH_matter)/src/system/SystemStats.cpp                                                    \
           $(SEARCH_matter)/src/system/SystemTimer.cpp                                                    \
           $(SEARCH_matter)/src/system/TLVPacketBufferBackingStore.cpp                                    \
           $(SEARCH_matter)/src/system/WakeEvent.cpp                                                      \
           $(SEARCH_matter)/src/tracing/registry.cpp                                                      \
           $(SEARCH_matter)/src/transport/CryptoContext.cpp                                               \
           $(SEARCH_matter)/src/transport/GroupPeerMessageCounter.cpp                                     \
           $(SEARCH_matter)/src/transport/SecureMessageCodec.cpp                                          \
           $(SEARCH_matter)/src/transport/SecureSession.cpp                                               \
           $(SEARCH_matter)/src/transport/SecureSessionTable.cpp                                          \
           $(SEARCH_matter)/src/transport/Session.cpp                                                     \
           $(SEARCH_matter)/src/transport/SessionHolder.cpp                                               \
           $(SEARCH_matter)/src/transport/SessionManager.cpp                                              \
           $(SEARCH_matter)/src/transport/TransportMgrBase.cpp                                            \
           $(SEARCH_matter)/src/transport/raw/BLE.cpp                                                     \
           $(SEARCH_matter)/src/transport/raw/MessageHeader.cpp                                           \
           $(SEARCH_matter)/src/transport/raw/PeerAddress.cpp                                             \
           $(SEARCH_matter)/src/transport/raw/TCP.cpp                                                     \
           $(SEARCH_matter)/src/transport/raw/UDP.cpp                                                     \
           $(SEARCH_matter)/zzz_generated/app-common/app-common/zap-generated/attributes/Accessors.cpp    \
           $(SEARCH_matter)/zzz_generated/app-common/app-common/zap-generated/cluster-objects.cpp
